### ISSUE TITLE
Replace ruby version in matrix mapping

### ISSUE THREAD

**Issue by pocke** [pocke/ci_against#10]
https://docs.travis-ci.com/user/languages/ruby/

```
language: ruby
rvm:
  - 1.9.2
  - jruby-18mode
  - jruby-19mode
  - jruby-head
jdk:
  - openjdk6
  - openjdk7
  - oraclejdk7
matrix:
  exclude:
    - rvm: 1.9.2
      jdk: openjdk6
    - rvm: 1.9.2
      jdk: openjdk7
    - rvm: 1.9.2
      jdk: oraclejdk7
```

Like this example
